<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ApplicationIcon>app.ico</ApplicationIcon>
	</PropertyGroup>
	<ItemGroup>
	  <AdditionalFiles Remove="app.manifest" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="app.ico" />
	</ItemGroup>

	<ItemGroup>
		<Using Remove="System.Windows.Forms" />
		<Using Remove="System.Drawing" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Resources\Bin\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="NAudio" Version="2.2.1" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="app.ico">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>

	<ItemGroup>
	  <ApplicationDefinition Update="App.xaml">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </ApplicationDefinition>
	</ItemGroup>

	<ItemGroup>
		<None Update="Resources\Bin\cygwin1.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Bin\geoip.db">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Bin\geosite.db">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Bin\iperf3.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Bin\sing-box.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Bin\wintun.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Flags\armenia.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Flags\estonia-gRPC.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Flags\estonia-tcp.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Flags\finland-gRPC.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Flags\finland-tcp.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Flags\germany-tcp.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Flags\germany-gRPC.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Flags\japan.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Flags\kazakhstan.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Flags\kyrgyzstan.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Flags\latvia-tcp.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Flags\latvia-gRPC.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Flags\netherlands-gRPC.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Flags\netherlands-tcp.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Flags\russia2.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\Flags\russia1.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>